local ops = vim.opt

ops.number = true
ops.relativenumber = true
ops.completeopt = "menuone"
ops.mouse = "a"
ops.backup = false
ops.compatible = false
ops.swapfile = false
ops.writebackup = false
ops.rnu = true
ops.title = true
ops.wrap = true
ops.number = true
ops.cursorline = true
ops.hidden = true
ops.list = true
ops.termguicolors = true
ops.undofile = true
ops.expandtab = true
ops.wrap = true
ops.cmdheight = 1
ops.laststatus = 2
ops.showtabline = 2
ops.listchars = "trail:·"
ops.background = "dark"
ops.textwidth = 120
ops.undodir = "~/.vim/undodir"
ops.guifont = "Hack,FiraCode\\ Nerd\\ Font"
ops.tabstop = 4
ops.shiftwidth = 4
ops.updatetime = 300
ops.timeoutlen = 500
ops.completeopt = { "menuone", "noinsert", "noselect" }
-- ops.shortmess = "filnxtToOFc"
ops.shortmess = ops.shortmess + "a"
ops.ignorecase = true
ops.smartcase = true
ops.signcolumn = "yes"
