#! /bin/sh

# Not needed, already in my xinitrc
# pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     true
bspc config click_to_focus          true
bspc config focused_border_color    '#1793D1'
bspc config pointer_modifier        mod1

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^8'
bspc rule -a i3lock layer=above

bspc desktop='^1' --focus

bspwmbar &
dunst &
feh --bg-center ~/Pictures/bg.png &
~/i3lock.sh
discord --no-sandbox &
