#! /bin/sh

# Not needed, already in my xinitrc
# pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     true
bspc config click_to_focus          true
bspc config focused_border_color    '#578fd6'
bspc config pointer_modifier        mod4
bspc config pointer_motion_interval 10

bspc rule -a Mumble state=floating
bspc rule -a Peek state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Dunst manage=off
bspc rule -a discord desktop='^8'
bspc rule -a mind desktop='^3'
bspc rule -a i3lock layer=above
bspc rule -a powermenu state=floating
bspc rule -a BTOP state=floating
bspc rule -a activate-linux layer=above
bspc rule -a Mechvibes hidden=on
bspc rule -a Floaterm state=floating

bspc desktop='^1' --focus
$HOME/.config/polybar/launch.sh
