anchor_to_edges = true
icon_theme = 'ePapirus-Dark'
position = 'bottom'

[[end]]
music_dir = '/home/tomvd/Music'
player_type = 'mpris'
type = 'music'

[end.truncate]
max_length = 100
mode = 'end'

[[end]]
type = 'clock'

[[end]]
type = 'script'
cmd = '~/.config/ironbar/volume.sh'

[[end]]
type = "tray"

[[start]]
all_monitors = false
type = 'workspaces'

[start.name_map]

[[start]]
show_icons = true
show_names = false
type = 'launcher'
favorites = ['firefox', 'discord', 'steam']
