vim.cmd [[inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"]]
vim.cmd [[inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"]]
vim.cmd [[hi TabLineFill guibg=#333333]]
vim.cmd [[hi! link LspDiagnosticsUnderlineInformation SpellRare]]
vim.cmd [[autocmd CursorHold * lua vim.lsp.diagnostic.show_line_diagnostics()]]
vim.cmd [[command! B buffers]]
vim.cmd [[command! Md set syntax=markdown]]
vim.cmd [[autocmd BufEnter * set number]]
vim.cmd [[autocmd BufEnter * set relativenumber]]
vim.cmd [[let mapleader = "\<Space>"]]
vim.cmd [[hi StatusLine guibg=#928374 guifg=#3c3836]]
vim.cmd [[set clipboard=unnamedplus]]
vim.cmd [[command! -nargs=* Ca !cargo <args>]]
vim.cmd [[let g:wiki_root = '~/wiki']]
vim.cmd [[au FileType markdown vmap <Leader><Bslash> :EasyAlign*<Bar><Enter>]]
vim.cmd [[autocmd BufEnter *.rs nnoremap J :lua require'rust-tools.join_lines'.join_lines()<CR>]]
-- vim.cmd [[imap <expr> <C-p>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>']]
-- vim.cmd [[smap <expr> <C-p>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>']]
vim.cmd [[autocmd ColorScheme * hi! link LspDiagnosticsUnderlineError SpellCap]]
vim.cmd [[autocmd ColorScheme * hi! link LspDiagnosticsUnderlineWarning SpellBad]]
vim.cmd [[autocmd ColorScheme * hi! link LspDiagnosticsUnderlineHint SpellRare]]
