return {}
-- Doesn't work for now, even on kitty. Maybe my config is conflicting with
-- the problem? Anyways, I'll stick to telescope for now.
-- return {
--     'romgrk/kirby.nvim',
--     event = 'VeryLazy',
--     keys = { '<leader>F', '<cmd>KirbyFilePicker<cr>' },
--     dependencies = {
--         { 'romgrk/fzy-lua-native', build = 'make' },
--         'romgrk/kui.nvim',
--     },
-- }
